### ISSUE TITLE
Issues regarding Instance Structure

### ISSUE THREAD

**Issue by birdx0810** [ExpectationMax/medical_ts_datasets#2]
Hi, I was wondering, from the example code provided in the README.rst file. 
Each iteration of the dataset consists of a dictionary containing two keys ['combined'] and ['target'] which I assume contains the data values and their respective labels. And for the values in ['combined'], the values are static_features, timestamps, features, feature_mask, and individual identifier. From the code below, I realized that the identifier values are not unique. Is this normal?

Code:
```
import tensorflow_datasets as tfds
import medical_ts_datasets

dataset = tfds.load(name='physionet2019', split='train')

data = list(phy12_train.as_numpy_iterator())

for i in range(10):
    data[i]['combined'][-1]
```

Outputs:
```
44
176
44
24
56
24
55
44
27
24
```

**Comment by birdx0810** [comment]
[Resolved]
I've found out it what I was printing was the sequence length.
Sorry for the trouble.

**Comment by ExpectationMax** [comment]
Hey birdx0810,

no worries. Happy to hear you figured it out.

Cheers,
Max
