### ISSUE TITLE
'tensorflow_datasets.core' has no attribute 'api_utils'

### ISSUE THREAD

**Issue by Nadni** [ExpectationMax/medical_ts_datasets#3]
Hi, I am trying to use your module but line 17 in 'util.py' generates the following error:
`File "C:\Program Files\Python38\lib\site-packages\medical_ts_datasets\util.py", line 17, in MedicalTsDatasetInfo
    @tfds.core.disallow_positional_args
AttributeError: module 'tensorflow_datasets.core' has no attribute 'disallow_positional_args'`

Maybe the function in question was moved in a newer version of tensorflow_datasets? Is there any way I can get around this problem?

thank you

**Comment by ExpectationMax** [comment]
Hey Nadni,

seems like the API was changed and `disallow_positional_args` is not included in newer versions of tfds.
The commit should fix this.

Cheers,
Max
