### ISSUE TITLE
MIMIC-III dataset

### ISSUE THREAD

**Issue by birdx0810** [ExpectationMax/medical_ts_datasets#4]
Hi, I would like yo inquire regarding usage of MIMIC-III dataset. I've got the access rights to the database `.csv` files, but I'm not sure how could I use the code in this repo as I do not have `mimic_benchmarking_mortality.csv` file.

https://github.com/ExpectationMax/medical_ts_datasets/blob/051d1cc4d9e657920e0ade31f04ea391571e3fdd/medical_ts_datasets/mimic_3_mortality.py#L104-L106

Thanks in advance.

**Comment by ExpectationMax** [comment]
Hi @birdx0810,

as written in the paper and in the description of the dataset, we are using the data generated via the MIMIC3-benchmarks preprocessing pipeline, which can be found [here](https://github.com/yerevann/mimic3-benchmarks).

The file `mimic_benchmarking_mortality.tar.gz` is obtained by running the preprocessing pipeline above on the data, and taring and compressing the output data folder (which contains the folders train and test and the files train_listfile.csv, val_listfile.csv and test_listfile.csv).

Feel free to reopen the issue in case you have any further questions.

Cheers,
Max
